# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dconsole < Formula
  desc "Transport-agnostic CLI proxy for Drupal — one command surface across ssh, ddev, lando, docker, kubectl, and subprocess plugins."
  homepage "https://github.com/dconsole/dconsole"
  version "0.3.1"
  license "GPL-2.0-only"

  on_macos do
    url "https://github.com/dconsole/dconsole/releases/download/v0.3.1/dconsole_0.3.1_darwin_all.tar.gz"
    sha256 "c26a37224c65b06e5ff01949ac2c69497467978608d3d3c1be6352c7dd4e15f3"

    define_method(:install) do
      bin.install "dconsole"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dconsole/dconsole/releases/download/v0.3.1/dconsole_0.3.1_linux_amd64.tar.gz"
      sha256 "1279f813bb7602f11737928c951445bd3c16d3151b3c005843f64bd4e293af9b"
      define_method(:install) do
        bin.install "dconsole"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dconsole/dconsole/releases/download/v0.3.1/dconsole_0.3.1_linux_arm64.tar.gz"
      sha256 "f83365bb52aefba37c844cdf06a7ece553932ea463af9163fb09db1caf6ada53"
      define_method(:install) do
        bin.install "dconsole"
      end
    end
  end

  test do
    assert_match "dconsole", shell_output("#{bin}/dconsole --version")
  end
end
