# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dconsole < Formula
  desc "Transport-agnostic CLI proxy for Drupal — one command surface across ssh, ddev, lando, docker, kubectl, and subprocess plugins."
  homepage "https://github.com/dconsole/dconsole"
  version "0.5.6"
  license "GPL-2.0-only"

  on_macos do
    url "https://github.com/dconsole/dconsole/releases/download/v0.5.6/dconsole_0.5.6_darwin_all.tar.gz"
    sha256 "750715f575f72a43d07d4586305666275df767e61f66a62ee24e60894d8469b7"

    define_method(:install) do
      bin.install "dconsole"
      # dcons is the short-form binary alias. Symlinked rather than
      # copied so a single binary update covers both names.
      bin.install_symlink "dconsole" => "dcons"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dconsole/dconsole/releases/download/v0.5.6/dconsole_0.5.6_linux_amd64.tar.gz"
      sha256 "24a41c2276c2ca0723bee40367629cd23c479da5eed0895d012184606e11ad36"
      define_method(:install) do
        bin.install "dconsole"
        # dcons is the short-form binary alias. Symlinked rather than
        # copied so a single binary update covers both names.
        bin.install_symlink "dconsole" => "dcons"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dconsole/dconsole/releases/download/v0.5.6/dconsole_0.5.6_linux_arm64.tar.gz"
      sha256 "8772fda7d893e55ea225e28c24be34cb4afedeede30c7a3b8a1f75591a286a36"
      define_method(:install) do
        bin.install "dconsole"
        # dcons is the short-form binary alias. Symlinked rather than
        # copied so a single binary update covers both names.
        bin.install_symlink "dconsole" => "dcons"
      end
    end
  end

  test do
    assert_match "dconsole", shell_output("#{bin}/dconsole --version")
    assert_match "dconsole", shell_output("#{bin}/dcons --version")
  end
end
