# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dconsole < Formula
  desc "Transport-agnostic CLI proxy for Drupal — one command surface across ssh, ddev, lando, docker, kubectl, and subprocess plugins."
  homepage "https://github.com/dconsole/dconsole"
  version "0.5.2"
  license "GPL-2.0-only"

  on_macos do
    url "https://github.com/dconsole/dconsole/releases/download/v0.5.2/dconsole_0.5.2_darwin_all.tar.gz"
    sha256 "d85ef4aa6f19787ec72d0a19c92e1665cb7dc11295fd14e5e54464b501c844cb"

    define_method(:install) do
      bin.install "dconsole"
      # dcons is the short-form binary alias. Symlinked rather than
      # copied so a single binary update covers both names.
      bin.install_symlink "dconsole" => "dcons"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dconsole/dconsole/releases/download/v0.5.2/dconsole_0.5.2_linux_amd64.tar.gz"
      sha256 "ed62e3703f58430925b18f08fe37ca38df025281905dd185b6a0cd476f0fc770"
      define_method(:install) do
        bin.install "dconsole"
        # dcons is the short-form binary alias. Symlinked rather than
        # copied so a single binary update covers both names.
        bin.install_symlink "dconsole" => "dcons"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dconsole/dconsole/releases/download/v0.5.2/dconsole_0.5.2_linux_arm64.tar.gz"
      sha256 "a5e079017b02f69bae2eb9d95f44ac83b4e94b0acfde6ceb6c245b6169430043"
      define_method(:install) do
        bin.install "dconsole"
        # dcons is the short-form binary alias. Symlinked rather than
        # copied so a single binary update covers both names.
        bin.install_symlink "dconsole" => "dcons"
      end
    end
  end

  test do
    assert_match "dconsole", shell_output("#{bin}/dconsole --version")
    assert_match "dconsole", shell_output("#{bin}/dcons --version")
  end
end
